// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzEGVZ-R4wnNhy6aRkWAHDtpqYL1OvKo',
    appId: '1:840779576091:web:08b386c46516c01b9d59be',
    messagingSenderId: '840779576091',
    projectId: 'mynotes-artur',
    authDomain: 'mynotes-artur.firebaseapp.com',
    storageBucket: 'mynotes-artur.appspot.com',
    measurementId: 'G-PY0BZ0VL8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OmJRVs_8OrdaN7ukJj9k2Z-buvm5EY4',
    appId: '1:840779576091:android:889d5d4ae916a4849d59be',
    messagingSenderId: '840779576091',
    projectId: 'mynotes-artur',
    storageBucket: 'mynotes-artur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1K_CrEBN69RLETqMrno48Es-6E5DKK80',
    appId: '1:840779576091:ios:b48ee365ee542b3e9d59be',
    messagingSenderId: '840779576091',
    projectId: 'mynotes-artur',
    storageBucket: 'mynotes-artur.appspot.com',
    iosBundleId: 'com.whatever.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1K_CrEBN69RLETqMrno48Es-6E5DKK80',
    appId: '1:840779576091:ios:0a8dd6b142da6bff9d59be',
    messagingSenderId: '840779576091',
    projectId: 'mynotes-artur',
    storageBucket: 'mynotes-artur.appspot.com',
    iosBundleId: 'com.whatever.mynotes.RunnerTests',
  );
}
